<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use App\Market;
use App\City;

class CreateMarketsTableAndLinkToCities extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        // Create markets table
        Schema::create('markets', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name')->unique();
            $table->softDeletes();
            $table->timestamps();
        });

        // Add market_id to cities table
        Schema::table('cities', function (Blueprint $table) {
            $table->integer('market_id')->nullable()->unsigned();
            $table->foreign('market_id')->references('id')->on('markets');
        });
       
        // Initialize market data
        $markets = [
            "Calgary",
            "Mesa",
            "Rocklin",
            "Bay Area",
            "Denver",
            "Fort Collins",
            "Jacksonville",
            "Fort Myers",
            "Miami",
            "Orlando",
            "Ormond Beach",
            "Royal Palm Beach",
            "Port St. Lucie",
            "Canton",
            "Trenton",
            "Atlanta",
            "Savannah",
            "Des Moines",
            "Cedar Rapids",
            "Spokane",
            "Rockford",
            "Barrington",
            "Chicago",
            "Yorkville",
            "Indianapolis",
            "Southern Kentucky",
            "Louisville",
            "Winnipeg",
            "West Michigan",
            "Detroit",
            "Grand Rapids",
            "Twin Cities",
            "Southern Minnesota",
            "St. Cloud",
            "St. Louis",
            "Farmington",
            "Wilmington",
            "Charlotte",
            "Raleigh",
            "Piedmont Triad",
            "Lincoln",
            "Las Vegas",
            "Dayton",
            "Columbus",
            "Cincinnati",
            "Oklahoma City",
            "Tulsa",
            "London",
            "Greater Toronto Area",
            "Whitby",
            "Portland",
            "Pittsburgh",
            "Philadelphia",
            "Columbia",
            "Greenville",
            "Nashville",
            "Memphis",
            "Dallas-Fort Worth",
            "Austin",
            "Houston",
            "Chippewa Falls",
            "Onalaska",
            "Milwaukee"
        ];

        // City Mapping Data
        // City IDs based on production dataset as of April 17, 2018
        $mappingData = [
            [140,"Calgary",1,"Alberta","AB","Calgary"],
            [175,"Calgary",1,"Alberta","AB","Calgary"],
            [177,"Okotoks",1,"Alberta","AB","Calgary"],
            [198,"Calgary",1,"Alberta","AB","Calgary"],
            [395,"Edmonton",1,"Alberta","AB",null],
            [450,"Okotoks",1,"Alberta","AB","Calgary"],
            [535,"Blackfalds",1,"Alberta","AB",null],
            [751,"Calgary",1,"Alberta","AB","Calgary"],
            [755,"Okotoks",1,"Alberta","AB","Calgary"],
            [191,"Anchorage",15,"Alaska","AK",null],
            [335,"Wasilla",15,"Alaska","AK",null],
            [562,"Fairbanks",15,"Alaska","AK",null],
            [41,"Suite D",14,"Alabama","AL",null],
            [49,"Royal Palm Beach",14,"Alabama","AL",null],
            [55,"Waite Park",14,"Alabama","AL",null],
            [61,"Suite 109",14,"Alabama","AL",null],
            [71,"St. Peters",14,"Alabama","AL",null],
            [82,"Westfield",14,"Alabama","AL",null],
            [113,"Grand Rapids",14,"Alabama","AL",null],
            [164,"Duncan",14,"Alabama","AL",null],
            [165,"Mobile",14,"Alabama","AL",null],
            [171,"West Palm Beach",14,"Alabama","AL",null],
            [173,"Mesa",14,"Alabama","AL",null],
            [176,"Okotoks",14,"Alabama","AL",null],
            [221,"Gulf Shores",14,"Alabama","AL",null],
            [222,"Fairhope",14,"Alabama","AL",null],
            [306,"Auburn",14,"Alabama","AL",null],
            [307,"Opelika",14,"Alabama","AL",null],
            [371,"Dothan",14,"Alabama","AL",null],
            [372,"midland city",14,"Alabama","AL",null],
            [378,"Homewood",14,"Alabama","AL",null],
            [413,"Pelham",14,"Alabama","AL",null],
            [414,"Meridianville",14,"Alabama","AL",null],
            [729,"Tuscaloosa",14,"Alabama","AL",null],
            [737,"Indianapolis",14,"Alabama","AL",null],
            [741,"Greenwood",14,"Alabama","AL",null],
            [743,"Fort Wayne",14,"Alabama","AL",null],
            [744,"Carmel",14,"Alabama","AL",null],
            [747,"Fishers",14,"Alabama","AL",null],
            [15,"Conway",17,"Arkansas","AR",null],
            [118,"Bentonville",17,"Arkansas","AR",null],
            [254,"Little Rock",17,"Arkansas","AR",null],
            [460,"Maumelle",17,"Arkansas","AR",null],
            [697,"Mountain Home",17,"Arkansas","AR",null],
            [724,"Rogers",17,"Arkansas","AR",null],
            [183,"Prescott Valley",16,"Arizona","AZ",null],
            [330,"Phoenix",16,"Arizona","AZ",null],
            [344,"Tucson",16,"Arizona","AZ",null],
            [506,"Glendale",16,"Arizona","AZ",null],
            [536,"Mesa",16,"Arizona","AZ","Mesa"],
            [578,"Flagstaff",16,"Arizona","AZ",null],
            [642,"Apache Junction",16,"Arizona","AZ",null],
            [730,"Scottsdale",16,"Arizona","AZ",null],
            [189,"Kelowna",2,"British Columbia","BC",null],
            [199,"West Kelowna",2,"British Columbia","BC",null],
            [202,"Vernon",2,"British Columbia","BC",null],
            [209,"Surrey",2,"British Columbia","BC",null],
            [352,"Coquitlam",2,"British Columbia","BC",null],
            [353,"Vancouver",2,"British Columbia","BC",null],
            [354,"Kamloops",2,"British Columbia","BC",null],
            [419,"Chilliwack",2,"British Columbia","BC",null],
            [461,"Victoria",2,"British Columbia","BC",null],
            [466,"Abbotsford",2,"British Columbia","BC",null],
            [469,"Maple Ridge",2,"British Columbia","BC",null],
            [526,"Langley",2,"British Columbia","BC",null],
            [626,"Williams Lake",2,"British Columbia","BC",null],
            [682,"Kel",2,"British Columbia","BC",null],
            [156,"San Jose",18,"California","CA","Bay Area"],
            [162,"Palo Alto",18,"California","CA",null],
            [211,"Norwalk",18,"California","CA",null],
            [236,"Citrus Heights",18,"California","CA",null],
            [239,"Westlake Village",18,"California","CA",null],
            [241,"El Cajon",18,"California","CA",null],
            [298,"Elk Grove",18,"California","CA",null],
            [315,"Sacramento",18,"California","CA",null],
            [318,"Campbell",18,"California","CA",null],
            [331,"Oakley",18,"California","CA",null],
            [332,"Discovery Bay",18,"California","CA",null],
            [336,"Coronado",18,"California","CA",null],
            [339,"Lancaster",18,"California","CA",null],
            [347,"vacaville",18,"California","CA",null],
            [351,"Rancho Mirage",18,"California","CA",null],
            [393,"Roseville",18,"California","CA",null],
            [400,"Paso Robles",18,"California","CA",null],
            [421,"San Diego",18,"California","CA",null],
            [422,"La Mesa",18,"California","CA",null],
            [427,"Huntington Beach",18,"California","CA",null],
            [448,"San Francisco",18,"California","CA",null],
            [456,"Santa Barbara",18,"California","CA",null],
            [457,"Los Angeles",18,"California","CA",null],
            [489,"Napa",18,"California","CA",null],
            [494,"Laguna Niguel",18,"California","CA",null],
            [503,"Hesperia",18,"California","CA",null],
            [508,"Rocklin",18,"California","CA","Rocklin"],
            [523,"Danville",18,"California","CA",null],
            [541,"Lincoln",18,"California","CA",null],
            [549,"Irvine",18,"California","CA",null],
            [553,"Redding",18,"California","CA",null],
            [566,"Encinitas",18,"California","CA",null],
            [577,"Thousand Oaks",18,"California","CA",null],
            [588,"San Leandro",18,"California","CA",null],
            [592,"Torrance",18,"California","CA",null],
            [593,"Santa Clara",18,"California","CA",null],
            [636,"Hayward",18,"California","CA",null],
            [646,"Ceres",18,"California","CA",null],
            [655,"Union City",18,"California","CA",null],
            [659,"Santa Cruz",18,"California","CA",null],
            [660,"Ben Lomond",18,"California","CA",null],
            [662,"Castro Valley",18,"California","CA",null],
            [669,"Laguna Hills",18,"California","CA",null],
            [672,"San Bruno",18,"California","CA",null],
            [674,"Oakland",18,"California","CA",null],
            [680,"El Centro",18,"California","CA",null],
            [687,"Pleasanton",18,"California","CA",null],
            [692,"Emerald Hills",18,"California","CA",null],
            [693,"San Carlos",18,"California","CA",null],
            [702,"Pleasant Hill",18,"California","CA",null],
            [703,"Fremont",18,"California","CA",null],
            [711,"Gardena",18,"California","CA",null],
            [22,"Thornton",19,"Colorado","CO","Denver"],
            [29,"Fort Collins",19,"Colorado","CO","Fort Collins"],
            [52,"Westminster",19,"Colorado","CO","Denver"],
            [86,"Denver",19,"Colorado","CO",null],
            [90,"Broomfield",19,"Colorado","CO","Denver"],
            [106,"Aurora",19,"Colorado","CO","Denver"],
            [145,"Brighton",19,"Colorado","CO","Denver"],
            [161,"Colorado Springs",19,"Colorado","CO",null],
            [174,"Englewood",19,"Colorado","CO",null],
            [195,"Longmont",19,"Colorado","CO",null],
            [224,"Lafayette",19,"Colorado","CO",null],
            [226,"Parker",19,"Colorado","CO",null],
            [227,"Centennial",19,"Colorado","CO",null],
            [231,"Littleton",19,"Colorado","CO",null],
            [290,"Wheat Ridge",19,"Colorado","CO",null],
            [442,"Louisville",19,"Colorado","CO",null],
            [573,"Evergreen",19,"Colorado","CO",null],
            [91,"Wallingford",20,"Connecticut","CT",null],
            [150,"Farmington",20,"Connecticut","CT",null],
            [255,"Manchester",20,"Connecticut","CT",null],
            [263,"Madison",20,"Connecticut","CT",null],
            [289,"South Windsor",20,"Connecticut","CT",null],
            [342,"Newington",20,"Connecticut","CT",null],
            [388,"Derby",20,"Connecticut","CT",null],
            [684,"Middletown",20,"Connecticut","CT",null],
            [725,"vernon",20,"Connecticut","CT",null],
            [726,"Tolland",20,"Connecticut","CT",null],
            [423,"Wilmington",21,"Delaware","DE",null],
            [12,"Jacksonville",22,"Florida","FL","Jacksonville"],
            [19,"Bonita Springs",22,"Florida","FL","Fort Myers"],
            [21,"Fort Myers",22,"Florida","FL","Fort Myers"],
            [33,"Naples",22,"Florida","FL","Fort Myers"],
            [53,"Tampa",22,"Florida","FL",null],
            [96,"Orlando",22,"Florida","FL",null],
            [100,"Venice",22,"Florida","FL",null],
            [117,"Ormond Beach",22,"Florida","FL","Ormond Beach"],
            [129,"Sarasota",22,"Florida","FL",null],
            [133,"Fort Lauderdale",22,"Florida","FL",null],
            [149,"Winter Springs",22,"Florida","FL",null],
            [167,"Kissimmee",22,"Florida","FL",null],
            [172,"Port Saint Lucie",22,"Florida","FL",null],
            [186,"Miami",22,"Florida","FL","Miami"],
            [188,"Palm Harbor",22,"Florida","FL",null],
            [245,"Orange City",22,"Florida","FL",null],
            [249,"Jupiter",22,"Florida","FL",null],
            [251,"Ft Myers",22,"Florida","FL",null],
            [253,"Cape Coral",22,"Florida","FL",null],
            [258,"Celebration",22,"Florida","FL","Orlando"],
            [262,"Key West",22,"Florida","FL",null],
            [282,"Clermont",22,"Florida","FL",null],
            [284,"Altamonte Springs",22,"Florida","FL",null],
            [285,"Clearwater",22,"Florida","FL",null],
            [286,"boynton Beach",22,"Florida","FL",null],
            [310,"New Port Richey",22,"Florida","FL",null],
            [324,"Osprey",22,"Florida","FL",null],
            [326,"Tallahassee",22,"Florida","FL",null],
            [358,"Palm Beach Gardens",22,"Florida","FL",null],
            [384,"Gainesville",22,"Florida","FL",null],
            [410,"Winter Park",22,"Florida","FL",null],
            [453,"Miami Beach",22,"Florida","FL",null],
            [454,"Wellington",22,"Florida","FL",null],
            [459,"Stuart",22,"Florida","FL",null],
            [496,"Port Orange",22,"Florida","FL",null],
            [499,"St. Petersburg",22,"Florida","FL",null],
            [500,"Oldsmar",22,"Florida","FL",null],
            [501,"Oldmar",22,"Florida","FL",null],
            [502,"Wesley Chapel",22,"Florida","FL",null],
            [507,"Trinity",22,"Florida","FL",null],
            [516,"The Villages",22,"Florida","FL",null],
            [519,"Jacksonville Beach",22,"Florida","FL",null],
            [537,"Haines City",22,"Florida","FL",null],
            [540,"DeLand",22,"Florida","FL",null],
            [544,"Lakeland",22,"Florida","FL",null],
            [548,"Brandon",22,"Florida","FL",null],
            [552,"Arcadia",22,"Florida","FL",null],
            [555,"Lake Placid",22,"Florida","FL",null],
            [568,"St Petersburg",22,"Florida","FL",null],
            [570,"Oakland",22,"Florida","FL",null],
            [580,"Windermere",22,"Florida","FL",null],
            [591,"Plant City",22,"Florida","FL",null],
            [598,"Dunedin",22,"Florida","FL",null],
            [603,"Maitland",22,"Florida","FL",null],
            [613,"St. Augustine",22,"Florida","FL",null],
            [620,"Gotha",22,"Florida","FL",null],
            [621,"Melbourne",22,"Florida","FL",null],
            [632,"Ponte Vedra",22,"Florida","FL",null],
            [638,"Daytona Beach",22,"Florida","FL",null],
            [676,"Indialantic",22,"Florida","FL",null],
            [679,"Marco Island",22,"Florida","FL",null],
            [688,"Ponte Vedra Beach",22,"Florida","FL",null],
            [710,"Odessa",22,"Florida","FL",null],
            [713,"Ft. Myers",22,"Florida","FL",null],
            [715,"Saint Cloud",22,"Florida","FL",null],
            [721,"Lakewood Ranch",22,"Florida","FL",null],
            [733,"Panama City","FL",22,"Florida","FL",null],
            [745,"Royal Palm Beach",22,"Florida","FL","Royal Palm Beach"],
            [750,"Estero",22,"Florida","FL",null],
            [752,"Panama City",22,"Florida","FL",null],
            [753,"St. Cloud",22,"Florida","FL",null],
            [28,"Powder Springs",23,"Georgia","GA","Atlanta"],
            [38,"Atlanta",23,"Georgia","GA","Atlanta"],
            [62,"Roswell",23,"Georgia","GA",null],
            [79,"Buford",23,"Georgia","GA",null],
            [127,"Brunswick",23,"Georgia","GA",null],
            [132,"Savannah",23,"Georgia","GA","Savannah"],
            [142,"Trenton",23,"Georgia","GA","Trenton"],
            [151,"Canton",23,"Georgia","GA","Canton"],
            [178,"Kennesaw",23,"Georgia","GA","Atlanta"],
            [212,"Dacula",23,"Georgia","GA",null],
            [267,"Woodstock",23,"Georgia","GA",null],
            [291,"Marietta",23,"Georgia","GA",null],
            [434,"Duluth",23,"Georgia","GA",null],
            [458,"Cumming",23,"Georgia","GA",null],
            [504,"Sandy Springs",23,"Georgia","GA",null],
            [505,"Norcross",23,"Georgia","GA",null],
            [607,"Augusta",23,"Georgia","GA",null],
            [622,"Gainesville",23,"Georgia","GA",null],
            [635,"Smyrna",23,"Georgia","GA",null],
            [639,"Milner",23,"Georgia","GA",null],
            [648,"Dublin",23,"Georgia","GA",null],
            [668,"Maretta",23,"Georgia","GA",null],
            [698,"Marieta",23,"Georgia","GA",null],
            [704,"White",23,"Georgia","GA",null],
            [708,"Acworth",23,"Georgia","GA",null],
            [437,"Kihei",24,"Hawaii","HI",null],
            [47,"Des Moines",28,"Iowa","IA","Des Moines"],
            [51,"Dubuque",28,"Iowa","IA",null],
            [131,"Cedar Rapids",28,"Iowa","IA","Cedar Rapids"],
            [155,"West Des Moines",28,"Iowa","IA","Des Moines"],
            [238,"Clive",28,"Iowa","IA",null],
            [261,"Pella",28,"Iowa","IA",null],
            [271,"Urbandale",28,"Iowa","IA",null],
            [301,"Davenport",28,"Iowa","IA",null],
            [348,"Dallas Center",28,"Iowa","IA",null],
            [349,"Grimes",28,"Iowa","IA",null],
            [387,"Waukee",28,"Iowa","IA",null],
            [425,"Harlan",28,"Iowa","IA",null],
            [444,"Charles City",28,"Iowa","IA",null],
            [490,"Windsor Heights",28,"Iowa","IA",null],
            [618,"Oskaloosa",28,"Iowa","IA",null],
            [727,"Ankeny",28,"Iowa","IA","Des Moines"],
            [46,"Boise",25,"Idaho","ID",null],
            [143,"Meridian",25,"Idaho","ID",null],
            [184,"Coeur d Alene",25,"Idaho","ID",null],
            [396,"Coeur d'Alene",25,"Idaho","ID","Spokane"],
            [542,"Idaho Falls",25,"Idaho","ID",null],
            [627,"Hayden",25,"Idaho","ID",null],
            [10,"Romeoville",26,"Illinois","IL","Chicago"],
            [54,"Yorkville",26,"Illinois","IL","Yorkville"],
            [56,"Rockford",26,"Illinois","IL","Rockford"],
            [72,"Normal",26,"Illinois","IL",null],
            [74,"St. Charles",26,"Illinois","IL","Chicago"],
            [104,"Aurora",26,"Illinois","IL",null],
            [112,"Shorewood",26,"Illinois","IL","Chicago"],
            [125,"Gurnee",26,"Illinois","IL",null],
            [128,"Barrington",26,"Illinois","IL","Barrington"],
            [130,"Minooka",26,"Illinois","IL",null],
            [152,"Peru",26,"Illinois","IL",null],
            [154,"Wheaton",26,"Illinois","IL","Chicago"],
            [205,"Chicago",26,"Illinois","IL",null],
            [223,"Orland Park",26,"Illinois","IL",null],
            [230,"Naperville",26,"Illinois","IL",null],
            [237,"Lockport",26,"Illinois","IL",null],
            [278,"MOKENA",26,"Illinois","IL",null],
            [300,"Joliet",26,"Illinois","IL",null],
            [303,"Libertyville",26,"Illinois","IL",null],
            [313,"West Dundee",26,"Illinois","IL",null],
            [321,"Peoria",26,"Illinois","IL",null],
            [340,"Moline",26,"Illinois","IL",null],
            [356,"Edwardsville",26,"Illinois","IL",null],
            [359,"Glendale Heights",26,"Illinois","IL",null],
            [424,"Glen Carbon",26,"Illinois","IL",null],
            [447,"Palos Heights",26,"Illinois","IL",null],
            [452,"Oak Lawn",26,"Illinois","IL",null],
            [472,"Crystal Lake",26,"Illinois","IL",null],
            [473,"Johnsburg",26,"Illinois","IL",null],
            [495,"Huntley",26,"Illinois","IL",null],
            [509,"Plainfield",26,"Illinois","IL",null],
            [556,"Bannockburn",26,"Illinois","IL",null],
            [558,"Woodridge",26,"Illinois","IL",null],
            [579,"Roscoe",26,"Illinois","IL",null],
            [581,"Machesney Park",26,"Illinois","IL",null],
            [582,"Bolingbrook",26,"Illinois","IL",null],
            [600,"Quincy",26,"Illinois","IL",null],
            [602,"Glen Ellyn",26,"Illinois","IL",null],
            [606,"Hoffman Estates",26,"Illinois","IL",null],
            [610,"Olney",26,"Illinois","IL",null],
            [637,"Carol Stream",26,"Illinois","IL",null],
            [643,"Coal Valley",26,"Illinois","IL",null],
            [644,"Springfield",26,"Illinois","IL",null],
            [651,"Freeport",26,"Illinois","IL",null],
            [653,"Coffeen",26,"Illinois","IL",null],
            [665,"Rock Island",26,"Illinois","IL",null],
            [673,"Champaign",26,"Illinois","IL",null],
            [707,"O'Fallon",26,"Illinois","IL",null],
            [728,"Evanston",26,"Illinois","IL",null],
            [36,"Fishers",27,"Indiana","IN","Indianapolis"],
            [42,"Greenwood",27,"Indiana","IN","Indianapolis"],
            [63,"Carmel",27,"Indiana","IN","Indianapolis"],
            [69,"Fort Wayne",27,"Indiana","IN",null],
            [95,"Indianapolis",27,"Indiana","IN","Indianapolis"],
            [468,"Crown Point",27,"Indiana","IN",null],
            [517,"columbus",27,"Indiana","IN",null],
            [630,"Ingalls",27,"Indiana","IN",null],
            [206,"Manhattan",29,"Kansas","KS",null],
            [295,"Leawood",29,"Kansas","KS",null],
            [345,"Olathe",29,"Kansas","KS",null],
            [369,"Wichita",29,"Kansas","KS",null],
            [370,"Goddard",29,"Kansas","KS",null],
            [391,"Overland Park",29,"Kansas","KS",null],
            [451,"Kansas City",29,"Kansas","KS",null],
            [527,"Lenexa",29,"Kansas","KS",null],
            [714,"Hiawatha",29,"Kansas","KS",null],
            [48,"Middletown",30,"Kentucky","KY","Louisville"],
            [126,"Danville",30,"Kentucky","KY",null],
            [170,"Bowling Green",30,"Kentucky","KY","Southern Kentucky"],
            [270,"Benton",30,"Kentucky","KY",null],
            [276,"Paducah",30,"Kentucky","KY",null],
            [279,"Lexington",30,"Kentucky","KY",null],
            [401,"Georgetown",30,"Kentucky","KY",null],
            [402,"Richmond",30,"Kentucky","KY",null],
            [418,"Morganfield",30,"Kentucky","KY",null],
            [539,"Frankfort",30,"Kentucky","KY",null],
            [575,"Fort Wright",30,"Kentucky","KY",null],
            [585,"Florence",30,"Kentucky","KY",null],
            [287,"Shreveport",31,"Louisiana","LA",null],
            [366,"Baton Rouge",31,"Louisiana","LA",null],
            [481,"Kaplan",31,"Louisiana","LA",null],
            [486,"Ponchatoula",31,"Louisiana","LA",null],
            [487,"Geismar",31,"Louisiana","LA",null],
            [550,"Lake Charles",31,"Louisiana","LA",null],
            [712,"Opelousas",31,"Louisiana","LA",null],
            [268,"East Longmeadow",34,"Massachusetts","MA",null],
            [367,"Salem",34,"Massachusetts","MA",null],
            [368,"Scituate",34,"Massachusetts","MA",null],
            [373,"Barre",34,"Massachusetts","MA",null],
            [379,"Lancaster",34,"Massachusetts","MA",null],
            [407,"Sandwich",34,"Massachusetts","MA",null],
            [554,"Swampscott",34,"Massachusetts","MA",null],
            [590,"Woburn",34,"Massachusetts","MA",null],
            [60,"Winnipeg",3,"Manitoba","MB","Winnipeg"],
            [203,"Oakbank",3,"Manitoba","MB",null],
            [204,"Steinbach",3,"Manitoba","MB",null],
            [328,"East St. Paul",3,"Manitoba","MB",null],
            [346,"St. Francois Xavier",3,"Manitoba","MB",null],
            [288,"Forest Hill",33,"Maryland","MD",null],
            [604,"college park",33,"Maryland","MD",null],
            [101,"Miami",32,"Maine","ME",null],
            [280,"Lewiston",32,"Maine","ME",null],
            [17,"Kentwood",35,"Michigan","MI","Grand Rapids"],
            [23,"Wixom",35,"Michigan","MI",null],
            [98,"Grandville",35,"Michigan","MI","Grand Rapids"],
            [141,"Warren",35,"Michigan","MI","Detroit"],
            [147,"Shelby Township",35,"Michigan","MI","West Michigan"],
            [166,"Grand Rapids",35,"Michigan","MI",null],
            [337,"Roseville",35,"Michigan","MI",null],
            [360,"Jackson",35,"Michigan","MI",null],
            [389,"Brownstown",35,"Michigan","MI",null],
            [403,"Harrison Township",35,"Michigan","MI",null],
            [404,"Harrison Twp.",35,"Michigan","MI",null],
            [416,"Lake Orion",35,"Michigan","MI",null],
            [429,"TROY",35,"Michigan","MI",null],
            [471,"Midland",35,"Michigan","MI",null],
            [518,"Highland",35,"Michigan","MI",null],
            [522,"Jenison",35,"Michigan","MI",null],
            [546,"Burton",35,"Michigan","MI",null],
            [645,"Alden",35,"Michigan","MI",null],
            [690,"East Jordan",35,"Michigan","MI",null],
            [691,"White Lake",35,"Michigan","MI",null],
            [731,"West Bloomfield",35,"Michigan","MI",null],
            [8,"Champlin",36,"Minnesota","MN","Twin Cities"],
            [35,"Missoula",36,"Minnesota","MN",null],
            [83,"North Branch",36,"Minnesota","MN",null],
            [114,"Saint Paul",36,"Minnesota","MN",null],
            [115,"Oakdale",36,"Minnesota","MN","Twin Cities"],
            [119,"Minnetonka",36,"Minnesota","MN","Twin Cities"],
            [120,"Rochester",36,"Minnesota","MN","Southern Minnesota"],
            [122,"Becker",36,"Minnesota","MN",null],
            [146,"Eagan",36,"Minnesota","MN","Twin Cities"],
            [234,"Roseville",36,"Minnesota","MN",null],
            [242,"Forest Lake",36,"Minnesota","MN",null],
            [272,"Buffalo",36,"Minnesota","MN",null],
            [275,"Maple Grove",36,"Minnesota","MN",null],
            [302,"Eden Prairie",36,"Minnesota","MN",null],
            [327,"Apple Valley",36,"Minnesota","MN",null],
            [364,"Blaine",36,"Minnesota","MN",null],
            [383,"savage",36,"Minnesota","MN",null],
            [408,"Otsego",36,"Minnesota","MN",null],
            [409,"Rogers",36,"Minnesota","MN",null],
            [417,"Brooklyn Park",36,"Minnesota","MN",null],
            [439,"Red Wing",36,"Minnesota","MN",null],
            [492,"Maplewood",36,"Minnesota","MN",null],
            [531,"Brownton",36,"Minnesota","MN",null],
            [557,"Minneapolis",36,"Minnesota","MN",null],
            [574,"Bloomington",36,"Minnesota","MN",null],
            [617,"Hastings",36,"Minnesota","MN",null],
            [628,"Stillwater",36,"Minnesota","MN",null],
            [629,"Oakland",36,"Minnesota","MN",null],
            [647,"Fairmont",36,"Minnesota","MN",null],
            [649,"excelsior",36,"Minnesota","MN",null],
            [658,"CENTER CITY",36,"Minnesota","MN",null],
            [667,"Burnsville",36,"Minnesota","MN",null],
            [718,"Edina",36,"Minnesota","MN",null],
            [736,"Waite Park",36,"Minnesota","MN","St. Cloud"],
            [757,"Woodbury",36,"Minnesota","MN","Twin Cities"],
            [2,"Ballwin",38,"Missouri","MO","St. Louis"],
            [18,"Kansas City",38,"Missouri","MO",null],
            [87,"Saint Louis",38,"Missouri","MO",null],
            [158,"Farmington",38,"Missouri","MO","Farmington"],
            [181,"Lees Summitt",38,"Missouri","MO",null],
            [228,"Wildwood",38,"Missouri","MO",null],
            [244,"Cape Girardeau",38,"Missouri","MO",null],
            [248,"Chesterfield",38,"Missouri","MO",null],
            [260,"St Louis",38,"Missouri","MO",null],
            [283,"Columbia",38,"Missouri","MO",null],
            [296,"Lees Summit",38,"Missouri","MO",null],
            [297,"Independence",38,"Missouri","MO",null],
            [311,"St. Charles",38,"Missouri","MO",null],
            [312,"Maryland Heights",38,"Missouri","MO",null],
            [317,"St Peters",38,"Missouri","MO",null],
            [341,"O'Fallon",38,"Missouri","MO",null],
            [465,"Ellisville",38,"Missouri","MO",null],
            [520,"Lee's Summitt",38,"Missouri","MO",null],
            [616,"Perryville",38,"Missouri","MO",null],
            [683,"Chesterfiel",38,"Missouri","MO",null],
            [695,"Saint Charles",38,"Missouri","MO",null],
            [696,"Manchester",38,"Missouri","MO",null],
            [701,"St. Peters",38,"Missouri","MO","St. Louis"],
            [742,"St. Louis",38,"Missouri","MO",null],
            [677,"Crosby",37,"Mississippi","MS",null],
            [700,"Madison",37,"Mississippi","MS",null],
            [250,"Helena",39,"Montana","MT",null],
            [608,"Kalispell",39,"Montana","MT",null],
            [694,"Ballwin",39,"Montana","MT",null],
            [754,"Missoula",39,"Montana","MT",null],
            [6,"Huntersville",46,"North Carolina","NC",null],
            [14,"Clemmons",46,"North Carolina","NC",null],
            [20,"Raleigh",46,"North Carolina","NC","Raleigh"],
            [25,"Winston Salem",46,"North Carolina","NC","Piedmont Triad"],
            [58,"Charlotte",46,"North Carolina","NC",null],
            [73,"Mooresville",46,"North Carolina","NC","Charlotte"],
            [78,"Garner",46,"North Carolina","NC",null],
            [81,"Durham",46,"North Carolina","NC",null],
            [105,"Wilmington",46,"North Carolina","NC","Wilmington"],
            [121,"Apex",46,"North Carolina","NC",null],
            [160,"Cary",46,"North Carolina","NC",null],
            [320,"Matthews",46,"North Carolina","NC",null],
            [381,"waxhaw",46,"North Carolina","NC","Charlotte"],
            [405,"Asheville",46,"North Carolina","NC",null],
            [412,"Cornelius",46,"North Carolina","NC",null],
            [428,"Greensboro",46,"North Carolina","NC","Piedmont Triad"],
            [532,"Maiden",46,"North Carolina","NC",null],
            [543,"Winston-Salem",46,"North Carolina","NC",null],
            [584,"Stanfield",46,"North Carolina","NC",null],
            [717,"Hampstead",46,"North Carolina","NC",null],
            [304,"Fargo",47,"North Dakota","ND",null],
            [382,"Pembina",47,"North Dakota","ND",null],
            [420,"Bismarck",47,"North Dakota","ND",null],
            [89,"Lincoln",40,"Nebraska","NE","Lincoln"],
            [274,"Omaha",40,"Nebraska","NE",null],
            [440,"O'neill",40,"Nebraska","NE",null],
            [631,"Bismarck",40,"Nebraska","NE",null],
            [374,"Plaistow",42,"New Hampshire","NH",null],
            [435,"Peterborough",42,"New Hampshire","NH",null],
            [37,"Stirling",43,"New Jersey","NJ",null],
            [134,"Denville",43,"New Jersey","NJ",null],
            [138,"Whippany",43,"New Jersey","NJ",null],
            [218,"Fair Lawn",43,"New Jersey","NJ",null],
            [445,"Brick",43,"New Jersey","NJ",null],
            [446,"Lanoka Harbor",43,"New Jersey","NJ",null],
            [455,"Pompton",43,"New Jersey","NJ",null],
            [474,"Point Pleasant",43,"New Jersey","NJ",null],
            [521,"Park Ridge",43,"New Jersey","NJ",null],
            [524,"Morristown",43,"New Jersey","NJ",null],
            [599,"Williamstown",43,"New Jersey","NJ",null],
            [623,"Fairfield",43,"New Jersey","NJ",null],
            [624,"Mine Hill",43,"New Jersey","NJ",null],
            [678,"Whitehouse Station",43,"New Jersey","NJ",null],
            [723,"Phillipsburg",43,"New Jersey","NJ",null],
            [159,"Las Vegas",41,"Nevada","NV","Las Vegas"],
            [482,"Reno",41,"Nevada","NV",null],
            [215,"New City",45,"New York","NY",null],
            [216,"Chestnut Ridge",45,"New York","NY",null],
            [256,"Fishkill",45,"New York","NY",null],
            [293,"Woodside",45,"New York","NY",null],
            [314,"Rochester",45,"New York","NY",null],
            [386,"Ithaca",45,"New York","NY",null],
            [397,"Brooklyn",45,"New York","NY",null],
            [415,"Baldwinsville",45,"New York","NY",null],
            [432,"Macedon",45,"New York","NY",null],
            [433,"Ontario",45,"New York","NY",null],
            [528,"New York",45,"New York","NY",null],
            [534,"Garden City",45,"New York","NY",null],
            [656,"Hopewell Junction",45,"New York","NY",null],
            [675,"Staten Island",45,"New York","NY",null],
            [44,"Lewis Center",48,"Ohio","OH",null],
            [57,"Columbus",48,"Ohio","OH",null],
            [59,"Troy",48,"Ohio","OH","Dayton"],
            [84,"Powell",48,"Ohio","OH","Columbus"],
            [93,"Marysville",48,"Ohio","OH","Columbus"],
            [94,"West Chester",48,"Ohio","OH","Cincinnati"],
            [192,"Brampton",48,"Ohio","OH",null],
            [325,"Cincinnati",48,"Ohio","OH",null],
            [334,"Milford",48,"Ohio","OH",null],
            [361,"Westerville",48,"Ohio","OH",null],
            [475,"Heath",48,"Ohio","OH",null],
            [476,"Newark",48,"Ohio","OH",null],
            [485,"Fairfield",48,"Ohio","OH",null],
            [510,"Springboro",48,"Ohio","OH",null],
            [567,"Wooster",48,"Ohio","OH",null],
            [699,"Tiffin",48,"Ohio","OH",null],
            [13,"Broken Arrow",49,"Oklahoma","OK","Tulsa"],
            [27,"Oklahoma City",49,"Oklahoma","OK","Oklahoma City"],
            [64,"Tulsa",49,"Oklahoma","OK",null],
            [168,"Duncan",49,"Oklahoma","OK",null],
            [179,"Norman",49,"Oklahoma","OK","Oklahoma City"],
            [220,"Edmond",49,"Oklahoma","OK",null],
            [441,"Owasso",49,"Oklahoma","OK",null],
            [513,"Stillwater",49,"Oklahoma","OK",null],
            [99,"Brampton",9,"Ontario","ON",null],
            [123,"Lucan",9,"Ontario","ON","London"],
            [124,"Toronto",9,"Ontario","ON","Greater Toronto Area"],
            [136,"Brantford",9,"Ontario","ON",null],
            [139,"Peterborough",9,"Ontario","ON",null],
            [180,"Richmond Hill",9,"Ontario","ON",null],
            [185,"London",9,"Ontario","ON","London"],
            [187,"Whitby",9,"Ontario","ON","Whitby"],
            [190,"Aurora",9,"Ontario","ON",null],
            [193,"Mississauga",9,"Ontario","ON",null],
            [200,"Thornhill",9,"Ontario","ON",null],
            [201,"Waterloo",9,"Ontario","ON",null],
            [208,"Barrie",9,"Ontario","ON",null],
            [214,"Komoka",9,"Ontario","ON",null],
            [252,"GUELPH",9,"Ontario","ON",null],
            [338,"St. Catharines",9,"Ontario","ON",null],
            [357,"Hamilton",9,"Ontario","ON",null],
            [362,"Sarnia",9,"Ontario","ON",null],
            [398,"Niagara Falls",9,"Ontario","ON",null],
            [498,"Lakeside",9,"Ontario","ON",null],
            [525,"Tecumseh",9,"Ontario","ON",null],
            [551,"Dunrobin",9,"Ontario","ON",null],
            [571,"Cambridge",9,"Ontario","ON",null],
            [572,"Kitchener",9,"Ontario","ON",null],
            [605,"Burlington",9,"Ontario","ON",null],
            [615,"Burlington", "Ontario","9","Ontario","ON",null],
            [652,"Grimsby",9,"Ontario","ON",null],
            [657,"tillsonburg",9,"Ontario","ON",null],
            [720,"Nobleton",9,"Ontario","ON",null],
            [734,"Ottawa",9,"Ontario","ON",null],
            [740,"335 Main Street East",9,"Ontario","ON",null],
            [756,"Cambridge2",9,"Ontario","ON",null],
            [5,"Eugene",50,"Oregon","OR",null],
            [77,"Salem",50,"Oregon","OR",null],
            [153,"Beaverton",50,"Oregon","OR","Portland"],
            [299,"Redmond",50,"Oregon","OR",null],
            [329,"Gresham",50,"Oregon","OR",null],
            [26,"Lititz",51,"Pennsylvania","PA",null],
            [32,"Brentwood",51,"Pennsylvania","PA","Pittsburgh"],
            [65,"Cranberry Township",51,"Pennsylvania","PA",null],
            [67,"Malvern",51,"Pennsylvania","PA","Philadelphia"],
            [80,"Pittsburgh",51,"Pennsylvania","PA",null],
            [376,"Sayre",51,"Pennsylvania","PA",null],
            [394,"Altoona",51,"Pennsylvania","PA",null],
            [411,"Kittanning",51,"Pennsylvania","PA",null],
            [430,"Wexford",51,"Pennsylvania","PA",null],
            [462,"Level Green",51,"Pennsylvania","PA",null],
            [463,"Greensburg",51,"Pennsylvania","PA",null],
            [493,"New Britain",51,"Pennsylvania","PA",null],
            [565,"Dresher",51,"Pennsylvania","PA",null],
            [595,"Butler",51,"Pennsylvania","PA",null],
            [601,"Harrisburg",51,"Pennsylvania","PA",null],
            [654,"NorthHampton",51,"Pennsylvania","PA",null],
            [689,"Renfrew",51,"Pennsylvania","PA",null],
            [716,"McMurray",51,"Pennsylvania","PA",null],
            [107,"San Juan",71,"Puerto Rico","PR",null],
            [157,"Caguas",71,"Puerto Rico","PR",null],
            [273,"guaynabo",71,"Puerto Rico","PR",null],
            [545,"Mayaguez",71,"Puerto Rico","PR",null],
            [569,"Hatillo",71,"Puerto Rico","PR",null],
            [719,"Aguada",71,"Puerto Rico","PR",null],
            [390,"mascouche",11,"Quebec","QC",null],
            [449,"Sherbrooke",11,"Quebec","QC",null],
            [533,"Laval",11,"Quebec","QC",null],
            [735,"Langelier",11,"Quebec","QC",null],
            [739,"Saint-Léonard",11,"Quebec","QC",null],
            [7,"Columbia",53,"South Carolina","SC","Columbia"],
            [43,"Mt. Pleasant",53,"South Carolina","SC",null],
            [50,"Greenville",53,"South Carolina","SC","Greenville"],
            [116,"Greensboro",53,"South Carolina","SC",null],
            [229,"Charleston",53,"South Carolina","SC",null],
            [265,"North Myrtle Beach",53,"South Carolina","SC",null],
            [266,"Little River",53,"South Carolina","SC",null],
            [281,"Florence",53,"South Carolina","SC",null],
            [308,"Lancaster",53,"South Carolina","SC",null],
            [385,"Simpsonville",53,"South Carolina","SC",null],
            [406,"Elgin",53,"South Carolina","SC",null],
            [488,"Fountain Inn",53,"South Carolina","SC",null],
            [497,"Rock Hill",53,"South Carolina","SC",null],
            [559,"Mount Pleasant",53,"South Carolina","SC",null],
            [611,"Inman",53,"South Carolina","SC",null],
            [612,"Spartanburg",53,"South Carolina","SC",null],
            [640,"Lexington",53,"South Carolina","SC",null],
            [34,"Sioux Falls",54,"South Dakota","SD",null],
            [213,"Dell Rapids",54,"South Dakota","SD",null],
            [586,"MITCHELL",54,"South Dakota","SD",null],
            [343,"La Ronge",12,"Saskatchewan","SK",null],
            [363,"Watson",12,"Saskatchewan","SK",null],
            [583,"Saskatoon",12,"Saskatchewan","SK",null],
            [9,"Nashville",55,"Tennessee","TN","Nashville"],
            [30,"Smyrna",55,"Tennessee","TN","Nashville"],
            [31,"Knoxville",55,"Tennessee","TN",null],
            [76,"Brentwood",55,"Tennessee","TN",null],
            [88,"Mount Juliet",55,"Tennessee","TN","Nashville"],
            [92,"Chattanooga",55,"Tennessee","TN",null],
            [110,"Memphis",55,"Tennessee","TN","Nashville"],
            [235,"CLARKSVILLE",55,"Tennessee","TN",null],
            [243,"Collierville",55,"Tennessee","TN",null],
            [247,"Murfreesboro",55,"Tennessee","TN",null],
            [277,"Hermitage",55,"Tennessee","TN",null],
            [305,"Franklin",55,"Tennessee","TN",null],
            [350,"Fayetteville",55,"Tennessee","TN",null],
            [377,"Cleveland",55,"Tennessee","TN",null],
            [392,"Goodlettsville",55,"Tennessee","TN",null],
            [436,"Soddy Daisy",55,"Tennessee","TN",null],
            [478,"Johnson City",55,"Tennessee","TN",null],
            [512,"Cookeville",55,"Tennessee","TN",null],
            [547,"Nolensville",55,"Tennessee","TN",null],
            [609,"Hixon",55,"Tennessee","TN",null],
            [619,"Dallas",55,"Tennessee","TN",null],
            [625,"Eagleville",55,"Tennessee","TN",null],
            [706,"Cordova",55,"Tennessee","TN",null],
            [749,"Trenton",55,"Tennessee","TN",null],
            [3,"Missouri City",56,"Texas","TX","Houston"],
            [16,"Denton",56,"Texas","TX","Dallas-Fort Worth"],
            [24,"Spring",56,"Texas","TX",null],
            [39,"Plano",56,"Texas","TX",null],
            [66,"Frisco",56,"Texas","TX",null],
            [68,"Fort Worth",56,"Texas","TX","Dallas-Fort Worth"],
            [70,"Arlington",56,"Texas","TX","Dallas-Fort Worth"],
            [75,"Austin",56,"Texas","TX","Austin"],
            [85,"Cedar Hill",56,"Texas","TX","Dallas-Fort Worth"],
            [108,"Houston",56,"Texas","TX","Houston"],
            [135,"McKinney",56,"Texas","TX",null],
            [137,"Coppell",56,"Texas","TX","Dallas-Fort Worth"],
            [144,"Round Rock",56,"Texas","TX",null],
            [148,"Dallas",56,"Texas","TX","Dallas-Fort Worth"],
            [196,"Comfort",56,"Texas","TX",null],
            [197,"Boerne",56,"Texas","TX",null],
            [207,"Amarillo",56,"Texas","TX",null],
            [219,"The Woodlands",56,"Texas","TX",null],
            [225,"Cypress",56,"Texas","TX",null],
            [240,"San Antonio",56,"Texas","TX",null],
            [246,"Tyler",56,"Texas","TX",null],
            [257,"Bee Cave",56,"Texas","TX",null],
            [259,"College Station",56,"Texas","TX",null],
            [264,"Cedar Park",56,"Texas","TX",null],
            [294,"Grapevine",56,"Texas","TX",null],
            [309,"Euless",56,"Texas","TX",null],
            [365,"Texarkana",56,"Texas","TX",null],
            [375,"Midland",56,"Texas","TX",null],
            [380,"Katy",56,"Texas","TX",null],
            [399,"Burleson",56,"Texas","TX",null],
            [477,"Henderson",56,"Texas","TX",null],
            [479,"Irving",56,"Texas","TX",null],
            [483,"Garland",56,"Texas","TX",null],
            [484,"Richmond",56,"Texas","TX",null],
            [576,"Georgetown",56,"Texas","TX",null],
            [589,"Allen",56,"Texas","TX",null],
            [594,"League City",56,"Texas","TX",null],
            [614,"Spicewood",56,"Texas","TX",null],
            [634,"Addison",56,"Texas","TX",null],
            [641,"Pearland",56,"Texas","TX",null],
            [661,"Richardson",56,"Texas","TX",null],
            [663,"Little Elm",56,"Texas","TX",null],
            [681,"Lantana",56,"Texas","TX",null],
            [685,"Pleasanton",56,"Texas","TX",null],
            [686,"Seabrook",56,"Texas","TX",null],
            [722,"Lewisville",56,"Texas","TX",null],
            [738,"Southlake",56,"Texas","TX","Dallas-Fort Worth"],
            [323,"Salt Lake City",57,"Utah","UT",null],
            [515,"Ogden",57,"Utah","UT",null],
            [529,"Kaysville",57,"Utah","UT",null],
            [530,"Fruit Heights",57,"Utah","UT",null],
            [587,"Vernal",57,"Utah","UT",null],
            [597,"Orem",57,"Utah","UT",null],
            [45,"Leesburg",59,"Virginia","VA",null],
            [319,"Forest",59,"Virginia","VA",null],
            [464,"Roanoke",59,"Virginia","VA",null],
            [470,"Danville",59,"Virginia","VA",null],
            [633,"Shelburne",59,"Virginia","VA",null],
            [97,"West Lakewood",60,"Washington","WA",null],
            [103,"Puyallup",60,"Washington","WA",null],
            [169,"Veradale",60,"Washington","WA",null],
            [182,"Spokane",60,"Washington","WA",null],
            [194,"Tacoma",60,"Washington","WA",null],
            [233,"Vancouver",60,"Washington","WA",null],
            [333,"Kennewick",60,"Washington","WA",null],
            [355,"Sumas",60,"Washington","WA",null],
            [511,"Richland",60,"Washington","WA",null],
            [560,"Poulsbo",60,"Washington","WA",null],
            [563,"Sequim",60,"Washington","WA",null],
            [4,"Eau Claire",62,"Wisconsin","WI",null],
            [11,"Chippewa Falls",62,"Wisconsin","WI","Chippewa Falls"],
            [40,"La Crosse",62,"Wisconsin","WI",null],
            [109,"Madison",62,"Wisconsin","WI","Milwaukee"],
            [163,"Germantown",62,"Wisconsin","WI",null],
            [232,"Waukesha",62,"Wisconsin","WI",null],
            [269,"Franklin",62,"Wisconsin","WI",null],
            [316,"Oshkosh",62,"Wisconsin","WI",null],
            [322,"Black River Falls",62,"Wisconsin","WI",null],
            [431,"Leopolis",62,"Wisconsin","WI",null],
            [438,"Prescott",62,"Wisconsin","WI",null],
            [467,"Delafied",62,"Wisconsin","WI",null],
            [491,"Marinette",62,"Wisconsin","WI",null],
            [514,"Manitowoc",62,"Wisconsin","WI",null],
            [538,"Thorp",62,"Wisconsin","WI",null],
            [561,"Muskego",62,"Wisconsin","WI",null],
            [596,"Abrams",62,"Wisconsin","WI",null],
            [650,"Fall Creek",62,"Wisconsin","WI",null],
            [664,"Albany",62,"Wisconsin","WI",null],
            [666,"Glendale",62,"Wisconsin","WI",null],
            [670,"Prairie du Sac WI",62,"Wisconsin","WI",null],
            [671,"Prairie du Sac",62,"Wisconsin","WI",null],
            [705,"Brookfield",62,"Wisconsin","WI",null],
            [709,"Hales Corners",62,"Wisconsin","WI",null],
            [758,"Hudson",62,"Wisconsin","WI",null],
            [217,"Cheyenne",63,"Wyoming","WY",null]
        ];

        foreach ($markets as $marketName) {
            $market = new Market();
            $market->name = $marketName;
            $market->save();

            // Add map market to city
            foreach ($mappingData as $mapping) {
                if ($mapping[5] === $marketName) {
                    $city = City::find($mapping[0]);
                    if ($city) {
                        $city->market_id = $market->id;
                        $city->save();
                    }
                }
            }
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        // Drop market_id column
        Schema::table('cities', function (Blueprint $table) {
            $table->dropForeign(['market_id']);
        });

        Schema::table('cities', function (Blueprint $table) {
            $table->dropColumn('market_id');
        });

        Schema::dropIfExists('markets');
    }
}
